services:
  rmq1:
    image: rabbitmq:4.2.3-management-alpine
    container_name: rmq1
    hostname: rmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: log-collector-cookie
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
       - /volumes/rmq1:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rmq2:
    image: rabbitmq:4.2.3-management-alpine
    container_name: rmq2
    hostname: rmq2
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: log-collector-cookie
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - volumes/rmq2:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rmq3:
    image: rabbitmq:4.2.3-management-alpine
    container_name: rmq3
    hostname: rmq3
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: log-collector-cookie
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - volumes/rmq3:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ch1:
    image: clickhouse/clickhouse-server:26.1-alpine
    container_name: ch1
    hostname: ch1
    restart: always
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DB: default
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/local.xml:ro
      - ./clickhouse/macro1.xml:/etc/clickhouse-server/config.d/macros.xml:ro
      - ./clickhouse/keeper1.xml:/etc/clickhouse-server/config.d/keeper.xml:ro
      - volumes/ch1-data:/var/lib/clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    ulimits:
      nproc: 65536
      nofile:
        soft: 252144
        hard: 252144
  ch2:
    image: clickhouse/clickhouse-server:26.1-alpine
    container_name: ch2
    hostname: ch2
    restart: always
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DB: default
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/local.xml:ro
      - ./clickhouse/macro2.xml:/etc/clickhouse-server/config.d/macros.xml:ro
      - ./clickhouse/keeper2.xml:/etc/clickhouse-server/config.d/keeper.xml:ro
      - volumes/ch2-data:/var/lib/clickhouse
    ports:
      - '8124:8123'
      - '9001:9000'
    ulimits:
      nproc: 65536
      nofile:
        soft: 252144
        hard: 252144
    depends_on:
      ch1:
        condition: service_started
  ch3:
    image: clickhouse/clickhouse-server:26.1-alpine
    container_name: ch3
    hostname: ch3
    restart: always
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DB: default
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/local.xml:ro
      - ./clickhouse/macro3.xml:/etc/clickhouse-server/config.d/macros.xml:ro
      - ./clickhouse/keeper3.xml:/etc/clickhouse-server/config.d/keeper.xml:ro
      - volumes/ch3-data:/var/lib/clickhouse
    ports:
      - '8125:8123'
      - '9002:9000'
    ulimits:
      nproc: 65536
      nofile:
        soft: 252144
        hard: 252144
    depends_on:
      ch1:
        condition: service_started

  generator:
    build:
      context: log-collector
      dockerfile: docker/Dockerfile.generator
    container_name: generator
    hostname: generator
    environment:
       GENERATOR_CONFIG_PATH: /etc/generator/config.yaml
       # variables from config file can be overrided with env variables
    volumes:
      - ./log-collector/configs/generator.yaml:/etc/generator/config.yaml:ro
    depends_on:
      rmq1:
        condition: service_healthy
      rmq2:
        condition: service_healthy
      rmq3:
        condition: service_healthy

  collector:
    build:
      context: log-collector
      dockerfile: docker/Dockerfile.collector
    container_name: collector
    hostname: collector
    restart: always
    environment:
       COLLECTOR_CONFIG_PATH: /etc/collector/config.yaml
       # variables from config file can be overrided with env variables
    volumes:
      - ./log-collector/configs/collector.yaml:/etc/collector/config.yaml:ro
    ports:
      - '8080:8080'
    depends_on:
      ch1:
        condition: service_started
      ch2:
        condition: service_started
      ch3:
        condition: service_started
      rmq1:
        condition: service_healthy
      rmq2:
        condition: service_healthy
      rmq3:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    ports:
      - "9090:9090"
    user: "${PROMETHEUS_UID}"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./volumes/prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    user: "${GRAFANA_UID}"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./volumes/grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus

  superset:
    build:
      context: superset
      dockerfile: Dockerfile.superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: "supersecretkey"
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
    volumes:
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py:ro
      - ./superset/superset_import:/app/import
    command: ["/entrypoint.sh"]
    depends_on:
      ch1:
        condition: service_started

include:
  - docker-compose-airflow.yaml
