global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'log-collector'
    static_configs:
      - targets: ['collector:8080']
    metrics_path: '/metrics'
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['ch1:9363']
    metrics_path: '/metrics'
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rmq1:15692']
    metrics_path: '/metrics'
